{{- if and .Values.scaling.enabled (empty .Values.scaling.cpu) .Values.scaling.pdb.enabled }}
apiVersion: policy/v1{{ if semverCompare "<1.21.0" .Capabilities.KubeVersion.Version }}beta1{{ end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "azp-agent.autoscaler.fullname" . }}
  labels:
    {{- include "azp-agent.labels" . | nindent 4 }}
    component: autoscaler
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "azp-agent.selector" . | nindent 6 }}
      component: autoscaler
{{- end }}
